# This is a basic workflow to help you get started with Actions

name: generate_evaluation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        
      - name: setup python
        uses: actions/setup-python@v2
        with: 
         python-version: 3.8 # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install ipython
          pip install seaborn
          pip install matplotlib
          pip install sparknlp
          pip install pyspark
          pip install spacy
          pip install stanza
          
      - name: execute py script 
        run: |
          python evaluation_notebook.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main          
